"""
Tests for Labelme IO module.
"""

import pytest
import json
import tempfile
import os
from pathlib import Path
import numpy as np

# Install opencv for testing
import sys

sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from src.core.labelme_io import LabelmeIO, MaskShape, ImageInfo


class TestLabelmeIO:
    """Tests for LabelmeIO class."""

    def test_read_bbox_json(self):
        """Test: Read BBox JSON file."""
        test_data = {
            "version": "5.10.1",
            "flags": {},
            "shapes": [
                {
                    "label": "worm",
                    "points": [[100.0, 200.0], [300.0, 400.0]],
                    "shape_type": "rectangle",
                    "group_id": 1,
                    "description": "",
                    "flags": {},
                    "mask": None,
                }
            ],
            "imagePath": "../images/test.jpg",
            "imageData": None,
            "imageHeight": 1080,
            "imageWidth": 1920,
        }

        with tempfile.NamedTemporaryFile(mode="w", suffix=".json", delete=False) as f:
            json.dump(test_data, f)
            json_path = f.name

        try:
            image_info, bbox_shapes = LabelmeIO.read_bbox_json(Path(json_path))

            assert image_info.image_path == "../images/test.jpg"
            assert image_info.image_height == 1080
            assert image_info.image_width == 1920
            assert len(bbox_shapes) == 1
            assert bbox_shapes[0].label == "worm"
            assert bbox_shapes[0].points == [[100.0, 200.0], [300.0, 400.0]]
            assert bbox_shapes[0].group_id == 1
        finally:
            os.unlink(json_path)

    def test_write_mask_json(self):
        """Test: Write Mask JSON file."""
        mask_shapes = [
            MaskShape(
                label="worm",
                points=[[100, 200], [150, 180], [200, 200]],
                group_id=1,
                description="Generated by SAM",
            )
        ]
        image_info = ImageInfo(
            image_path="../images/test.jpg", image_height=1080, image_width=1920
        )

        with tempfile.NamedTemporaryFile(mode="w", suffix=".json", delete=False) as f:
            json_path = f.name

        try:
            LabelmeIO.write_mask_json(Path(json_path), mask_shapes, image_info)

            # Verify by reading
            with open(json_path, "r") as f:
                data = json.load(f)

            assert data["imagePath"] == "../images/test.jpg"
            assert data["imageHeight"] == 1080
            assert len(data["shapes"]) == 1
            assert data["shapes"][0]["shape_type"] == "polygon"
            assert data["shapes"][0]["label"] == "worm"
        finally:
            os.unlink(json_path)

    def test_mask_to_polygon(self):
        """Test: Convert mask to polygon."""
        # Install opencv in venv for this test
        try:
            import cv2
        except ImportError:
            pytest.skip("cv2 not available")

        # Create a simple circular mask
        mask = np.zeros((100, 100), dtype=np.uint8)
        cv2.circle(mask, (50, 50), 30, 1, -1)

        points = LabelmeIO.mask_to_polygon(mask)

        # Verify result
        assert len(points) > 10
        assert all(len(p) == 2 for p in points)

        # Verify points are in reasonable range (circle center at 50,50 with radius 30)
        xs = [p[0] for p in points]
        ys = [p[1] for p in points]
        assert 15 <= min(xs) <= 25  # Circle left edge ~ 20
        assert 75 <= max(xs) <= 85  # Circle right edge ~ 80
        assert 15 <= min(ys) <= 25
        assert 75 <= max(ys) <= 85

    def test_read_multiple_bboxes(self):
        """Test: Read file with multiple bboxes."""
        test_data = {
            "version": "5.10.1",
            "shapes": [
                {
                    "label": "worm",
                    "points": [[100, 100], [200, 200]],
                    "shape_type": "rectangle",
                    "group_id": 1,
                },
                {
                    "label": "worm",
                    "points": [[300, 300], [400, 400]],
                    "shape_type": "rectangle",
                    "group_id": 2,
                },
            ],
            "imagePath": "../images/test.jpg",
            "imageHeight": 500,
            "imageWidth": 500,
        }

        with tempfile.NamedTemporaryFile(mode="w", suffix=".json", delete=False) as f:
            json.dump(test_data, f)
            json_path = f.name

        try:
            image_info, bbox_shapes = LabelmeIO.read_bbox_json(Path(json_path))

            assert len(bbox_shapes) == 2
            assert bbox_shapes[0].group_id == 1
            assert bbox_shapes[1].group_id == 2
        finally:
            os.unlink(json_path)


class TestMaskToPolygon:
    """Tests specifically for mask_to_polygon function."""

    def test_empty_mask(self):
        """Test: Empty mask returns empty list."""
        mask = np.zeros((100, 100), dtype=np.uint8)
        points = LabelmeIO.mask_to_polygon(mask)
        assert points == [] or len(points) == 0

    def test_rectangle_mask(self):
        """Test: Rectangle mask."""
        try:
            import cv2
        except ImportError:
            pytest.skip("cv2 not available")

        mask = np.zeros((100, 100), dtype=np.uint8)
        mask[20:80, 30:70] = 1

        points = LabelmeIO.mask_to_polygon(mask)

        assert len(points) >= 4

    def test_complex_shape(self):
        """Test: Complex shape."""
        try:
            import cv2
        except ImportError:
            pytest.skip("cv2 not available")

        mask = np.zeros((200, 200), dtype=np.uint8)
        cv2.ellipse(mask, (100, 100), (60, 40), 45, 0, 360, 1, -1)

        points = LabelmeIO.mask_to_polygon(mask)

        assert len(points) > 20
