"""
Tests for Labelme IO module.
"""

import base64
import json
import os
import tempfile
from pathlib import Path

import pytest
import numpy as np

# Import module to test
import sys

sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from src.core.labelme_io import LabelmeIO, MaskShape, ImageInfo


class TestLabelmeIO:
    """Tests for LabelmeIO class."""

    def test_read_bbox_json(self):
        """Test: Read bbox JSON file."""
        test_data = {
            "version": "5.10.1",
            "flags": {},
            "shapes": [
                {
                    "label": "worm",
                    "points": [[100.0, 200.0], [300.0, 400.0]],
                    "shape_type": "rectangle",
                    "group_id": 1,
                    "description": "",
                    "flags": {},
                }
            ],
            "imagePath": "../images/test.jpg",
            "imageData": None,
            "imageHeight": 1080,
            "imageWidth": 1920,
        }

        with tempfile.NamedTemporaryFile(mode="w", suffix=".json", delete=False) as f:
            json.dump(test_data, f)
            json_path = f.name

        try:
            image_info, bbox_shapes = LabelmeIO.read_bbox_json(Path(json_path))

            assert image_info.image_path == "../images/test.jpg"
            assert image_info.image_height == 1080
            assert image_info.image_width == 1920
            assert len(bbox_shapes) == 1
            assert bbox_shapes[0].label == "worm"
            assert bbox_shapes[0].points == [[100.0, 200.0], [300.0, 400.0]]
            assert bbox_shapes[0].group_id == 1
        finally:
            os.unlink(json_path)

    def test_write_mask_json(self):
        """Test: Write mask JSON file using Labelme mask shape."""
        mask_shapes = [
            MaskShape(
                label="worm",
                points=[[100, 200], [150, 240]],
                group_id=1,
                description="Generated by SAM",
                shape_type="mask",
                mask="dGVzdA==",
            )
        ]
        image_info = ImageInfo(
            image_path="../images/test.jpg", image_height=1080, image_width=1920
        )

        with tempfile.NamedTemporaryFile(mode="w", suffix=".json", delete=False) as f:
            json_path = f.name

        try:
            LabelmeIO.write_mask_json(Path(json_path), mask_shapes, image_info)

            with open(json_path, "r") as f:
                data = json.load(f)

            assert data["imagePath"] == "../images/test.jpg"
            assert data["imageHeight"] == 1080
            assert len(data["shapes"]) == 1
            assert data["shapes"][0]["shape_type"] == "mask"
            assert data["shapes"][0]["label"] == "worm"
            assert data["shapes"][0]["mask"] == "dGVzdA=="
        finally:
            os.unlink(json_path)

    def test_read_multiple_bboxes(self):
        """Test: Read file with multiple bboxes."""
        test_data = {
            "version": "5.10.1",
            "shapes": [
                {
                    "label": "worm",
                    "points": [[100, 100], [200, 200]],
                    "shape_type": "rectangle",
                    "group_id": 1,
                },
                {
                    "label": "worm",
                    "points": [[300, 300], [400, 400]],
                    "shape_type": "rectangle",
                    "group_id": 2,
                },
            ],
            "imagePath": "../images/test.jpg",
            "imageHeight": 500,
            "imageWidth": 500,
        }

        with tempfile.NamedTemporaryFile(mode="w", suffix=".json", delete=False) as f:
            json.dump(test_data, f)
            json_path = f.name

        try:
            image_info, bbox_shapes = LabelmeIO.read_bbox_json(Path(json_path))
            assert len(bbox_shapes) == 2
            assert bbox_shapes[0].group_id == 1
            assert bbox_shapes[1].group_id == 2
        finally:
            os.unlink(json_path)


class TestMaskEncoding:
    """Tests for Labelme mask encoding helper."""

    def test_mask_to_labelme_mask(self):
        """Test: Convert binary mask to Labelme mask payload."""
        try:
            import cv2
        except ImportError:
            pytest.skip("cv2 not available")

        mask = np.zeros((20, 30), dtype=np.uint8)
        mask[5:10, 7:14] = 1

        points, mask_b64 = LabelmeIO.mask_to_labelme_mask(mask)

        assert points == [[7.0, 5.0], [13.0, 9.0]]
        assert isinstance(mask_b64, str)
        assert len(mask_b64) > 0

        png_data = base64.b64decode(mask_b64)
        decoded = cv2.imdecode(
            np.frombuffer(png_data, dtype=np.uint8), cv2.IMREAD_GRAYSCALE
        )
        assert decoded.shape == (5, 7)
        assert decoded.max() == 255
