"""
Tests for Labelme postprocessing adapter.
"""

import json
from pathlib import Path

import cv2
import numpy as np

import sys

sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from src.core.labelme_io import LabelmeIO
from src.postprocess.edge_refiner import EdgeOptimizationConfig
from src.postprocess.labelme_adapter import (
    build_output_path,
    collect_json_files,
    decode_labelme_mask,
    default_output_path,
    optimize_labelme_mask_file,
)


class TestLabelmeAdapter:
    """Tests for file-level Labelme mask adaptation."""

    def test_decode_labelme_mask_round_trip(self):
        """Test: Decode encoded mask payload into a full-size mask."""
        mask = np.zeros((20, 30), dtype=np.uint8)
        mask[5:10, 7:14] = 1

        points, mask_b64 = LabelmeIO.mask_to_labelme_mask(mask)
        decoded = decode_labelme_mask(mask_b64, points, 20, 30)

        assert np.array_equal(decoded, mask)

    def test_optimize_labelme_mask_file_writes_output(self, tmp_path):
        """Test: Optimize a file while preserving Labelme imagePath semantics."""
        image = np.zeros((100, 100, 3), dtype=np.uint8)
        target_mask = np.zeros((100, 100), dtype=np.uint8)
        input_mask = np.zeros((100, 100), dtype=np.uint8)

        cv2.rectangle(image, (30, 30), (70, 70), (255, 255, 255), -1)
        cv2.rectangle(target_mask, (30, 30), (70, 70), 1, -1)
        cv2.rectangle(input_mask, (26, 26), (66, 66), 1, -1)

        image_path = tmp_path / "images" / "sample.png"
        input_json_path = tmp_path / "masks" / "sample.json"
        output_json_path = tmp_path / "optimized" / "sample.json"
        image_path.parent.mkdir(parents=True)
        input_json_path.parent.mkdir(parents=True)

        cv2.imwrite(str(image_path), image)
        points, mask_b64 = LabelmeIO.mask_to_labelme_mask(input_mask)
        input_json_path.write_text(
            json.dumps(
                {
                    "version": "5.10.1",
                    "flags": {},
                    "shapes": [
                        {
                            "label": "mask",
                            "points": points,
                            "group_id": 0,
                            "shape_type": "mask",
                            "description": "Generated by SAM",
                            "flags": {"sam_generated": True},
                            "mask": mask_b64,
                        }
                    ],
                    "imagePath": "../images/sample.png",
                    "imageHeight": 100,
                    "imageWidth": 100,
                    "imageData": None,
                },
                indent=2,
            )
        )

        stats = optimize_labelme_mask_file(
            input_json_path,
            output_json_path,
            EdgeOptimizationConfig(
                search_radius=8,
                foreground_erode=2,
                background_dilate=4,
                gaussian_kernel_size=5,
                canny_low_threshold=50,
                canny_high_threshold=150,
                min_area_ratio=0.5,
                max_area_ratio=1.5,
            ),
        )

        assert stats["updated_shapes"] == 1
        data = json.loads(output_json_path.read_text())
        assert data["imagePath"] == "../images/sample.png"

    def test_path_helpers_support_single_file_and_relative_structure(self, tmp_path):
        """Test: Path helpers preserve current CLI behavior."""
        input_json = tmp_path / "input" / "0002" / "0988-5.json"
        input_json.parent.mkdir(parents=True)
        input_json.write_text("{}")

        assert default_output_path(input_json) == input_json.with_name("0988-5.edge_optimized.json")
        assert collect_json_files(input_json) == [input_json]
        assert build_output_path(input_json, tmp_path / "input", tmp_path / "output") == (
            tmp_path / "output" / "0002" / "0988-5.json"
        )
