"""
Tests for edge-assisted mask optimization.
"""

import json
from pathlib import Path

import cv2
import numpy as np

# Import module to test
import sys

sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from src.core.labelme_io import LabelmeIO
from src.core.mask_edge_optimizer import (
    EdgeOptimizationConfig,
    decode_labelme_mask,
    optimize_labelme_mask_file,
    refine_mask_with_edges,
    smooth_binary_mask,
)


def _iou(mask_a: np.ndarray, mask_b: np.ndarray) -> float:
    """Calculate IoU between two binary masks."""
    mask_a = mask_a > 0
    mask_b = mask_b > 0
    union = np.logical_or(mask_a, mask_b).sum()
    if union == 0:
        return 1.0
    intersection = np.logical_and(mask_a, mask_b).sum()
    return float(intersection) / float(union)


def _boundary_complexity(mask: np.ndarray) -> int:
    """Approximate jaggedness by counting horizontal and vertical boundary changes."""
    mask = mask.astype(np.uint8)
    horizontal = np.count_nonzero(mask[:, 1:] != mask[:, :-1])
    vertical = np.count_nonzero(mask[1:, :] != mask[:-1, :])
    return int(horizontal + vertical)


class TestMaskEdgeOptimizer:
    """Tests for edge-assisted mask optimization helpers."""

    @staticmethod
    def _synthetic_refine_config() -> EdgeOptimizationConfig:
        """Use a stable config for synthetic regression tests."""
        return EdgeOptimizationConfig(
            search_radius=8,
            foreground_erode=2,
            background_dilate=4,
            gaussian_kernel_size=5,
            canny_low_threshold=50,
            canny_high_threshold=150,
            min_area_ratio=0.5,
            max_area_ratio=1.5,
        )

    def test_decode_labelme_mask_round_trip(self):
        """Test: Decode Labelme mask payload back into full-size mask."""
        mask = np.zeros((20, 30), dtype=np.uint8)
        mask[5:10, 7:14] = 1

        points, mask_b64 = LabelmeIO.mask_to_labelme_mask(mask)
        decoded = decode_labelme_mask(mask_b64, points, 20, 30)

        assert decoded.shape == (20, 30)
        assert np.array_equal(decoded, mask)

    def test_refine_mask_with_edges_improves_iou_on_synthetic_image(self):
        """Test: Edge-assisted refinement improves alignment on simple contrast edges."""
        image = np.zeros((100, 100, 3), dtype=np.uint8)
        target_mask = np.zeros((100, 100), dtype=np.uint8)
        input_mask = np.zeros((100, 100), dtype=np.uint8)

        cv2.rectangle(image, (30, 30), (70, 70), (255, 255, 255), -1)
        cv2.rectangle(target_mask, (30, 30), (70, 70), 1, -1)
        cv2.rectangle(input_mask, (26, 26), (66, 66), 1, -1)

        refined_mask = refine_mask_with_edges(
            image,
            input_mask,
            self._synthetic_refine_config(),
        )

        assert _iou(refined_mask, target_mask) > _iou(input_mask, target_mask)

    def test_optimize_labelme_mask_file_updates_mask_payload(self, tmp_path):
        """Test: Optimize a Labelme mask JSON against its source image."""
        image = np.zeros((100, 100, 3), dtype=np.uint8)
        target_mask = np.zeros((100, 100), dtype=np.uint8)
        input_mask = np.zeros((100, 100), dtype=np.uint8)

        cv2.rectangle(image, (30, 30), (70, 70), (255, 255, 255), -1)
        cv2.rectangle(target_mask, (30, 30), (70, 70), 1, -1)
        cv2.rectangle(input_mask, (26, 26), (66, 66), 1, -1)

        image_path = tmp_path / "images" / "sample.png"
        input_json_path = tmp_path / "masks" / "sample.json"
        output_json_path = tmp_path / "optimized" / "sample.json"
        image_path.parent.mkdir(parents=True)
        input_json_path.parent.mkdir(parents=True)

        cv2.imwrite(str(image_path), image)
        points, mask_b64 = LabelmeIO.mask_to_labelme_mask(input_mask)
        input_data = {
            "version": "5.10.1",
            "flags": {},
            "shapes": [
                {
                    "label": "mask",
                    "points": points,
                    "group_id": 0,
                    "shape_type": "mask",
                    "description": "Generated by SAM",
                    "flags": {"sam_generated": True},
                    "mask": mask_b64,
                }
            ],
            "imagePath": "../images/sample.png",
            "imageHeight": 100,
            "imageWidth": 100,
            "imageData": None,
        }
        input_json_path.write_text(json.dumps(input_data, indent=2))

        stats = optimize_labelme_mask_file(
            input_json_path,
            output_json_path,
            self._synthetic_refine_config(),
        )

        assert stats["updated_shapes"] == 1
        output_data = json.loads(output_json_path.read_text())
        assert output_data["imagePath"] == "../images/sample.png"
        assert output_data["shapes"][0]["label"] == "mask"

        output_mask = decode_labelme_mask(
            output_data["shapes"][0]["mask"],
            output_data["shapes"][0]["points"],
            output_data["imageHeight"],
            output_data["imageWidth"],
        )
        assert _iou(output_mask, target_mask) > _iou(input_mask, target_mask)

    def test_smooth_binary_mask_reduces_boundary_complexity(self):
        """Test: Binary mask smoothing reduces stair-step boundary complexity."""
        mask = np.zeros((40, 40), dtype=np.uint8)
        for offset in range(12):
            x_start = 6 + offset
            x_end = 17 + offset + (offset % 2)
            y_start = 6 + offset
            y_end = y_start + 2
            mask[y_start:y_end, x_start:x_end] = 1

        smoothed = smooth_binary_mask(mask, blur_kernel_size=5, morph_radius=1)

        assert _boundary_complexity(smoothed) < _boundary_complexity(mask)
        area_ratio = float(np.count_nonzero(smoothed)) / float(np.count_nonzero(mask))
        assert 0.8 <= area_ratio <= 1.2

    def test_refine_mask_with_cavity_recovery_restores_enclosed_hole(self):
        """Test: Cavity recovery reopens enclosed background inside a filled mask."""
        image = np.full((100, 100, 3), 180, dtype=np.uint8)
        target_mask = np.zeros((100, 100), dtype=np.uint8)
        input_mask = np.zeros((100, 100), dtype=np.uint8)

        cv2.circle(target_mask, (50, 50), 20, 1, -1)
        cv2.circle(target_mask, (50, 50), 9, 0, -1)
        cv2.circle(input_mask, (50, 50), 20, 1, -1)

        image[target_mask > 0] = (60, 60, 60)

        config = EdgeOptimizationConfig(
            search_radius=6,
            foreground_erode=4,
            background_dilate=2,
            gaussian_kernel_size=3,
            canny_low_threshold=1000,
            canny_high_threshold=2000,
            min_area_ratio=0.3,
            max_area_ratio=1.5,
            smoothing_kernel_size=3,
            smoothing_morph_radius=0,
            enable_cavity_recovery=True,
            cavity_min_area=25,
            cavity_min_distance=2,
            cavity_intensity_margin=5.0,
        )

        refined_mask = refine_mask_with_edges(image, input_mask, config)

        assert _iou(refined_mask, target_mask) > _iou(input_mask, target_mask)

    def test_refine_mask_with_cavity_recovery_preserves_valid_solid_mask(self):
        """Test: Cavity recovery does not carve a hole from a valid solid object."""
        image = np.full((100, 100, 3), 180, dtype=np.uint8)
        target_mask = np.zeros((100, 100), dtype=np.uint8)
        input_mask = np.zeros((100, 100), dtype=np.uint8)

        cv2.circle(target_mask, (50, 50), 20, 1, -1)
        input_mask[:] = target_mask
        image[target_mask > 0] = (60, 60, 60)

        config = EdgeOptimizationConfig(
            search_radius=6,
            foreground_erode=4,
            background_dilate=2,
            gaussian_kernel_size=3,
            canny_low_threshold=1000,
            canny_high_threshold=2000,
            min_area_ratio=0.3,
            max_area_ratio=1.5,
            smoothing_kernel_size=3,
            smoothing_morph_radius=0,
            enable_cavity_recovery=True,
            cavity_min_area=25,
            cavity_min_distance=2,
            cavity_intensity_margin=5.0,
        )

        refined_mask = refine_mask_with_edges(image, input_mask, config)

        assert np.array_equal(refined_mask, input_mask)

    def test_refine_mask_with_shell_removal_trims_residual_shell(self):
        """Test: Shell removal trims a thin background-like shell after cavity recovery."""
        image = np.full((120, 120, 3), 180, dtype=np.uint8)
        target_mask = np.zeros((120, 120), dtype=np.uint8)
        input_mask = np.zeros((120, 120), dtype=np.uint8)

        cv2.circle(target_mask, (60, 60), 24, 1, -1)
        cv2.circle(target_mask, (60, 60), 15, 0, -1)
        cv2.rectangle(target_mask, (62, 31), (72, 60), 0, -1)
        cv2.circle(input_mask, (60, 60), 24, 1, -1)

        image[input_mask > 0] = (60, 60, 60)
        cv2.circle(image, (60, 60), 8, (180, 180, 180), -1)
        image[31:61, 62:73] = (120, 120, 120)

        cavity_only_config = EdgeOptimizationConfig(
            search_radius=6,
            foreground_erode=4,
            background_dilate=2,
            gaussian_kernel_size=3,
            canny_low_threshold=1000,
            canny_high_threshold=2000,
            min_area_ratio=0.3,
            max_area_ratio=1.5,
            smoothing_kernel_size=3,
            smoothing_morph_radius=0,
            enable_cavity_recovery=True,
            cavity_min_area=25,
            cavity_min_distance=2,
            cavity_intensity_margin=5.0,
        )

        shell_config = EdgeOptimizationConfig(
            search_radius=6,
            foreground_erode=4,
            background_dilate=2,
            gaussian_kernel_size=3,
            canny_low_threshold=1000,
            canny_high_threshold=2000,
            min_area_ratio=0.3,
            max_area_ratio=1.5,
            smoothing_kernel_size=3,
            smoothing_morph_radius=0,
            enable_cavity_recovery=True,
            cavity_min_area=25,
            cavity_min_distance=2,
            cavity_intensity_margin=5.0,
            enable_shell_removal=True,
            shell_max_thickness=12,
            shell_background_cost_multiplier=1.0,
        )

        cavity_only_mask = refine_mask_with_edges(image, input_mask, cavity_only_config)
        shell_mask = refine_mask_with_edges(image, input_mask, shell_config)

        assert _iou(shell_mask, target_mask) > _iou(cavity_only_mask, target_mask)
