"""
Single-item processing workflow.
"""

from pathlib import Path
from typing import Callable, List, Optional
import logging

import cv2
import numpy as np

from ..models.sam_wrapper import SAMWrapper
from .data_manager import DataItem, DataManager
from .label_reader import LabelReader
from .labelme_io import LabelmeIO, MaskShape
from .result_writer import ResultWriter
from .types import ProcessingResult

logger = logging.getLogger(__name__)


class ItemProcessor:
    """Process one dataset item from image+labels to output masks."""

    def __init__(
        self,
        data_manager: DataManager,
        sam_wrapper: SAMWrapper,
        label_reader: LabelReader,
        result_writer: ResultWriter,
        skip_empty_labels: bool = True,
        image_loader: Optional[Callable[[Path], Optional[np.ndarray]]] = None,
    ):
        self.data_manager = data_manager
        self.sam_wrapper = sam_wrapper
        self.label_reader = label_reader
        self.result_writer = result_writer
        self.skip_empty_labels = skip_empty_labels
        self.image_loader = image_loader or self._default_image_loader

    @staticmethod
    def _default_image_loader(image_path: Path) -> Optional[np.ndarray]:
        """Load an image from disk."""
        return cv2.imread(str(image_path))

    @staticmethod
    def _build_mask_shapes(
        bbox_shapes: List,
        sam_results: List[dict],
    ) -> List[MaskShape]:
        """Convert SAM results to Labelme mask shapes."""
        mask_shapes = []
        for i, (bbox_shape, sam_result) in enumerate(zip(bbox_shapes, sam_results)):
            mask_array = np.array(sam_result.get("mask", []), dtype=np.uint8)
            points, encoded_mask = LabelmeIO.mask_to_labelme_mask(mask_array)

            mask_shapes.append(
                MaskShape(
                    label="mask",
                    points=points,
                    group_id=bbox_shape.group_id or i,
                    description="Generated by SAM",
                    flags={"sam_generated": True},
                    shape_type="mask",
                    mask=encoded_mask,
                )
            )
        return mask_shapes

    def process(
        self,
        data_item: DataItem,
        image: Optional[np.ndarray] = None,
    ) -> ProcessingResult:
        """Process a single dataset item."""
        image_path = self.data_manager.images_dir / data_item.relative_path
        label_path = data_item.bbox_path

        if label_path is None or not label_path.exists():
            return ProcessingResult(
                data_item=data_item,
                success=False,
                error_message=f"BBox file not found: {label_path}",
            )

        try:
            loaded_image = image if image is not None else self.image_loader(image_path)
            if loaded_image is None:
                return ProcessingResult(
                    data_item=data_item,
                    success=False,
                    error_message=f"Failed to load image: {image_path}",
                )
            image_height, image_width = loaded_image.shape[:2]
        except Exception as e:
            return ProcessingResult(
                data_item=data_item,
                success=False,
                error_message=f"Failed to load image: {e}",
            )

        try:
            loaded_annotations = self.label_reader.read_label_file(
                label_path=label_path,
                image_path=image_path,
                image_height=image_height,
                image_width=image_width,
            )
        except Exception as e:
            return ProcessingResult(
                data_item=data_item,
                success=False,
                error_message=f"Failed to read bbox: {e}",
            )

        image_info = loaded_annotations.image_info
        bbox_shapes = loaded_annotations.bbox_shapes

        if not bbox_shapes:
            if self.skip_empty_labels:
                logger.info(f"Skipping {data_item.image_id}: No bbox shapes found")
                return ProcessingResult(
                    data_item=data_item,
                    success=True,
                    mask_shapes=[],
                )
            return ProcessingResult(
                data_item=data_item,
                success=False,
                error_message="No bbox shapes found",
            )

        try:
            bboxes = [[p[0][0], p[0][1], p[1][0], p[1][1]] for p in [shape.points for shape in bbox_shapes]]
            sam_results = self.sam_wrapper.predict(loaded_image, bboxes)
        except Exception as e:
            return ProcessingResult(
                data_item=data_item,
                success=False,
                error_message=f"SAM inference failed: {e}",
            )

        try:
            mask_shapes = self._build_mask_shapes(bbox_shapes, sam_results)
        except Exception as e:
            return ProcessingResult(
                data_item=data_item,
                success=False,
                error_message=f"Failed to create mask shapes: {e}",
            )

        try:
            output_paths = self.result_writer.write_outputs(
                data_item=data_item,
                image_path=image_path,
                image_info=image_info,
                bbox_shapes=bbox_shapes,
                mask_shapes=mask_shapes,
            )
            if output_paths.mask_json_path is not None:
                logger.info(f"Saved mask to {output_paths.mask_json_path}")
            if output_paths.combined_json_path is not None:
                logger.info(f"Saved combined output to {output_paths.combined_json_path}")
        except Exception as e:
            return ProcessingResult(
                data_item=data_item,
                success=False,
                error_message=f"Failed to save mask: {e}",
            )

        return ProcessingResult(data_item=data_item, success=True, mask_shapes=mask_shapes)
